apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lpb2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-lpb2@sha256:e1be6662a937e182ecf7982d0a11e5603c1b1a0207ceab6a492c7a6b437336bd
        name: my-nodejs
        resources: {}
status: {}
